### PR TITLE
Removed the pom type from the dependency

### PR DESCRIPTION
**Pull request by letscodehu**
Removed the pom type from the dependency as it wouldn't work that way.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Can you please explain why it would not work? We have that line in every java library so we probably want to remove it everywhere.

**Comment by Rich-Taylor-oss** [comment]
The default artifact type is jar, and it is correct and consistent with gradle and other examples.

This pull request should be merged.

**Comment by letscodehu** [comment]
@vmihailenco sorry for the late response. So the main problem with the pom packaging type is that it does not contains its own compiled sources, only the dependencies. Therefore if you include it, it'll have all the transitive dependencies, but not the library itself.

**Comment by vmihailenco** [comment]
Thanks

**Pull request merged**
